/**
 * Self-contained HTML report: title block, assembly diagram (optional PNG
 * data URL), BOM, per-harness wiring tables, cutlist and netlist. Print-
 * friendly so the same document drives the PDF export.
 */
import type { Project } from './types'
import type { LibraryLike } from './derivation'
import { buildBom, bomTotals } from './bom'
import { formatMoney } from './currency'
import { cutlist, netlist, wiringTable } from './reports'

function escHtml(s: string | number | undefined): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function table(headers: string[], rows: (string | number | undefined)[][]): string {
  const head = headers.map((h) => `<th>${escHtml(h)}</th>`).join('')
  const body = rows
    .map((r) => `<tr>${r.map((c) => `<td>${escHtml(c)}</td>`).join('')}</tr>`)
    .join('\n')
  return `<table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`
}

export interface ReportOptions {
  /** PNG data URL of the assembly diagram, embedded when provided. */
  diagramPng?: string
  slackMm?: number
}

export function buildHtmlReport(
  lib: LibraryLike,
  project: Project,
  opts: ReportOptions = {}
): string {
  const date = new Date().toISOString().slice(0, 10)
  const bomRows = buildBom(project, lib)
  const totals = bomTotals(bomRows)
  const cut = cutlist(lib, project, opts.slackMm ?? 0)
  const nets = netlist(lib, project)

  const harnessSections = project.harnesses
    .map((h) => {
      const rows = wiringTable(lib, project, h)
      return `
<section>
  <h2>Harness — ${escHtml(h.name)}</h2>
  ${h.description ? `<p class="muted">${escHtml(h.description)}</p>` : ''}
  ${table(
    ['Wire', 'From', 'Pin', 'Signal', 'To', 'Pin', 'Signal', 'Color', 'Gauge', 'Wire Part', 'Length (mm)', 'Twisted'],
    rows.map((r) => [
      r.wire,
      `${r.fromDevice} · ${r.fromPort}`,
      r.fromPin,
      r.fromSignal,
      `${r.toDevice} · ${r.toPort}`,
      r.toPin,
      r.toSignal,
      r.color,
      r.gauge,
      r.wirePart,
      r.lengthMm ?? '—',
      r.twistedWith
    ])
  )}
  ${h.notes ? `<p class="notes"><strong>Notes:</strong> ${escHtml(h.notes)}</p>` : ''}
</section>`
    })
    .join('\n')

  const costLines = [...totals.costByCurrency.entries()]
    .map(([currency, amount]) => escHtml(formatMoney({ amount, currency })))
    .join(', ')

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>${escHtml(project.name)} — WireWeaver Report</title>
<style>
  * { box-sizing: border-box; }
  body { font: 13px/1.45 -apple-system, "Segoe UI", Roboto, sans-serif; color: #1a1d23; margin: 32px; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  h2 { font-size: 15px; margin: 28px 0 8px; border-bottom: 2px solid #1a1d23; padding-bottom: 4px; }
  table { border-collapse: collapse; width: 100%; margin: 8px 0; }
  th, td { border: 1px solid #c6c9d0; padding: 4px 8px; text-align: left; vertical-align: top; }
  th { background: #eef0f4; font-weight: 600; }
  section { break-inside: avoid; }
  .muted { color: #5a5f6a; }
  .notes { background: #f6f7f9; padding: 8px; border-left: 3px solid #8b8f98; }
  .titleblock { display: flex; justify-content: space-between; gap: 24px; border: 2px solid #1a1d23; padding: 12px 16px; margin-bottom: 24px; }
  .titleblock dl { margin: 0; display: grid; grid-template-columns: auto auto; gap: 2px 12px; font-size: 12px; }
  .titleblock dt { color: #5a5f6a; }
  .titleblock dd { margin: 0; font-weight: 600; }
  img.diagram { max-width: 100%; border: 1px solid #c6c9d0; margin: 8px 0; }
  @media print { body { margin: 12mm; } }
</style>
</head>
<body>
<div class="titleblock">
  <div>
    <h1>${escHtml(project.name)}</h1>
    ${project.description ? `<div class="muted">${escHtml(project.description)}</div>` : ''}
  </div>
  <dl>
    <dt>Revision</dt><dd>${escHtml(project.revision || '—')}</dd>
    <dt>Author</dt><dd>${escHtml(project.author || '—')}</dd>
    <dt>Date</dt><dd>${escHtml(date)}</dd>
    <dt>Generated by</dt><dd>WireWeaver</dd>
  </dl>
</div>

${opts.diagramPng ? `<section><h2>Assembly</h2><img class="diagram" src="${opts.diagramPng}" alt="Assembly diagram"></section>` : ''}

<section>
<h2>Bill of Materials</h2>
${table(
  ['Category', 'Name', 'Internal PN', 'Manufacturer', 'MPN', 'Qty', 'Unit Cost', 'Weight (g)'],
  bomRows.map((r) => [
    r.category,
    r.name,
    r.ipn,
    r.manufacturer,
    r.mpn,
    r.quantity,
    formatMoney(r.cost),
    r.weightGrams ?? ''
  ])
)}
<p class="muted">Total weight: ${escHtml(totals.weightGrams)} g${costLines ? ` · Total cost: ${costLines}` : ''}</p>
</section>

${harnessSections}

<section>
<h2>Cutlist${opts.slackMm ? ` (includes ${escHtml(opts.slackMm)} mm slack per cut)` : ''}</h2>
${table(
  ['Wire Part', 'Gauge', 'Color', 'Cut Length (mm)', 'Qty'],
  cut.map((r) => [r.wirePart, r.gauge, r.color, r.cutLengthMm ?? 'unknown', r.quantity])
)}
</section>

<section>
<h2>Netlist</h2>
${table(
  ['Net', 'Device', 'Port', 'Pin', 'Signal'],
  nets.flatMap((net) => net.nodes.map((n) => [net.name, n.device, n.port, n.pin, n.signal]))
)}
</section>
</body>
</html>`
}
