/**
 * Export a harness as a WireViz (https://github.com/wireviz/WireViz) YAML
 * file. Endpoints become connectors (A, B, C, …); wires between each endpoint
 * pair are grouped into one cable; connections map pins pairwise.
 *
 * Strings are emitted as JSON string literals, which are valid YAML scalars —
 * no quoting edge cases.
 */
import type { Harness, Project } from './types'
import { endLabel, isWire } from './types'
import type { LibraryLike } from './derivation'
import { resolveAllEndpoints } from './derivation'

function y(s: string): string {
  return JSON.stringify(s)
}

function yList(items: (string | number)[]): string {
  return `[${items.map((i) => (typeof i === 'number' ? String(i) : y(i))).join(', ')}]`
}

export function wirevizYaml(lib: LibraryLike, project: Project, harness: Harness): string {
  const { resolved } = resolveAllEndpoints(lib, project.deviceInstances, harness)
  const lines: string[] = [
    `# ${harness.name} — generated by WireWeaver from project ${y(project.name)}`,
    ''
  ]

  // ----- connectors -----
  lines.push('connectors:')
  const connLabels = new Map<string, string>() // end label -> WireViz key
  for (let i = 0; i < harness.endpoints.length; i++) {
    const label = endLabel(i)
    const key = label.toUpperCase()
    connLabels.set(label, key)
    const re = resolved.get(label)
    lines.push(`  ${key}:`)
    if (!re) {
      lines.push(`    notes: ${y('unresolved endpoint')}`)
      continue
    }
    if (re.connector) {
      lines.push(`    type: ${y(re.connector.name)}`)
      if (re.connector.manufacturerPartNumber) {
        lines.push(`    mpn: ${y(re.connector.manufacturerPartNumber)}`)
      }
      lines.push(`    pincount: ${re.connector.positions}`)
    }
    if (re.pins.length > 0) {
      lines.push(`    pins: ${yList(re.pins.map((p) => p.position))}`)
      lines.push(`    pinlabels: ${yList(re.pins.map((p) => p.signal || ' '))}`)
    }
    lines.push(`    notes: ${y(`${re.instance.label} · ${re.port.name}`)}`)
  }

  // ----- cables: one per endpoint pair that has wires -----
  interface Group {
    key: string
    a: string
    b: string
    wires: { aPin: number; bPin: number; color?: string; wirePartId?: string }[]
  }
  const groups = new Map<string, Group>()
  for (const w of harness.wires) {
    // Normalize so (a,b) and (b,a) share a group; keep pin sides consistent.
    const flip = w.from.end > w.to.end
    const a = flip ? w.to.end : w.from.end
    const b = flip ? w.from.end : w.to.end
    const aPin = flip ? w.to.position : w.from.position
    const bPin = flip ? w.from.position : w.to.position
    const key = `${a}${b}`
    const g = groups.get(key) ?? { key, a, b, wires: [] }
    g.wires.push({ aPin, bPin, color: w.color, wirePartId: w.wirePartId })
    groups.set(key, g)
  }

  lines.push('')
  lines.push('cables:')
  for (const g of groups.values()) {
    const name = `CABLE_${g.key.toUpperCase()}`
    lines.push(`  ${name}:`)
    lines.push(`    wirecount: ${g.wires.length}`)
    const colors = g.wires.map((w) => w.color ?? '')
    if (colors.some((c) => c)) lines.push(`    colors: ${yList(colors)}`)
    const partId = g.wires.find((w) => w.wirePartId)?.wirePartId
    const part = partId ? lib.parts[partId] : undefined
    if (part && isWire(part) && part.gauge) lines.push(`    gauge: ${y(part.gauge)}`)
    const seg = harness.segments.find(
      (s) =>
        (s.fromEnd === g.a && s.toEnd === g.b) || (s.fromEnd === g.b && s.toEnd === g.a)
    )
    if (seg?.lengthMm != null) {
      lines.push(`    length: ${Math.round(seg.lengthMm) / 1000}`) // WireViz uses meters
    }
  }

  // ----- connections -----
  lines.push('')
  lines.push('connections:')
  for (const g of groups.values()) {
    const name = `CABLE_${g.key.toUpperCase()}`
    lines.push('  -')
    lines.push(`    - ${connLabels.get(g.a)}: ${yList(g.wires.map((w) => w.aPin))}`)
    lines.push(`    - ${name}: ${yList(g.wires.map((_, i) => i + 1))}`)
    lines.push(`    - ${connLabels.get(g.b)}: ${yList(g.wires.map((w) => w.bPin))}`)
  }

  return lines.join('\n') + '\n'
}
